"use client";
import { useState } from "react";
import { emptyOpportunityDraft, type OpportunityDraft } from "./volunteer-types";

export default function VolunteerOpportunityForm({ initial, campaigns, busy, onClose, onSave }: { initial?: OpportunityDraft; campaigns: { id: string; title: string }[]; busy: boolean; onClose: () => void; onSave: (draft: OpportunityDraft) => void }) {
  const [draft, setDraft] = useState(initial ?? emptyOpportunityDraft);
  const field = (key: keyof OpportunityDraft, label: string, type = "text") => <label className="grid gap-1 text-sm font-bold text-slate-700">{label}<input type={type} value={draft[key]} onChange={(e) => setDraft({ ...draft, [key]: e.target.value })} className="min-h-11 rounded-xl border border-slate-200 px-3 font-normal" /></label>;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/45 p-4"><form onSubmit={(e) => { e.preventDefault(); onSave(draft); }} className="max-h-[95vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-2xl font-bold text-raz-dark">{initial ? "עריכת הזדמנות" : "יצירת הזדמנות"}</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{field("title", "כותרת")}{field("startsAt", "תאריך ושעה", "datetime-local")}{field("location", "מקום")}{field("capacity", "קיבולת", "number")}{field("calendarUrl", "קישור ליומן", "url")}<label className="grid gap-1 text-sm font-bold text-slate-700">קמפיין<select value={draft.campaignId} onChange={(e) => setDraft({ ...draft, campaignId: e.target.value })} className="min-h-11 rounded-xl border border-slate-200 px-3 font-normal"><option value="">ללא קמפיין</option>{campaigns.map((campaign) => <option key={campaign.id} value={campaign.id}>{campaign.title}</option>)}</select></label><label className="grid gap-1 text-sm font-bold text-slate-700 md:col-span-2">תיאור<textarea value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} className="min-h-24 rounded-xl border border-slate-200 p-3 font-normal" /></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl px-4 py-2 font-bold">ביטול</button><button disabled={busy || !draft.title.trim()} className="rounded-xl bg-raz-teal px-5 py-2 font-bold text-white disabled:opacity-50">{busy ? "שומר..." : "שמירה"}</button></div></form></div>;
}
