"use client";
import { useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Users } from "lucide-react";
import VolunteerOpportunityForm from "./VolunteerOpportunityForm";
import { emptyOpportunityDraft, type OpportunityDraft, type VolunteerOpportunity, type VolunteerSignup, type VolunteerStatus } from "./volunteer-types";
import { getVolunteerDashboard, saveVolunteerOpportunity, setVolunteerOpportunityStatus, setVolunteerSignupStatus } from "@/lib/supabase/queries-volunteers";

type CampaignOption = { id: string; title: string };
export default function VolunteerDashboard({ kind, campaigns }: { kind: "ngo" | "community"; campaigns: CampaignOption[] }) {
  const [opportunities, setOpportunities] = useState<VolunteerOpportunity[]>([]); const [signups, setSignups] = useState<VolunteerSignup[]>([]);
  const [editing, setEditing] = useState<VolunteerOpportunity | null>(null); const [open, setOpen] = useState(false); const [selected, setSelected] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = async () => { try { const data = await getVolunteerDashboard(kind); setOpportunities(data.opportunities); setSignups(data.signups); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load volunteers"); } };
  useEffect(() => { let active = true; getVolunteerDashboard(kind).then((data) => { if (active) { setOpportunities(data.opportunities); setSignups(data.signups); setError(""); } }).catch((cause: unknown) => { if (active) setError(cause instanceof Error ? cause.message : "Unable to load volunteers"); }); return () => { active = false; }; }, [kind]);
  const selectedSignups = useMemo(() => signups.filter((signup) => signup.opportunity_id === selected), [selected, signups]);
  const draftFor = (row: VolunteerOpportunity | null): OpportunityDraft => row ? { title: row.title, description: row.description, startsAt: row.starts_at?.slice(0, 16) ?? "", location: row.location ?? "", calendarUrl: row.calendar_url ?? "", capacity: row.capacity?.toString() ?? "", campaignId: row.campaign_id ?? "" } : emptyOpportunityDraft;
  async function save(draft: OpportunityDraft) { setBusy(true); try { await saveVolunteerOpportunity(draft, editing?.id); setOpen(false); setEditing(null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save opportunity"); } finally { setBusy(false); } }
  async function close(row: VolunteerOpportunity) { setBusy(true); try { await setVolunteerOpportunityStatus(row.id, row.status === "closed" ? "active" : "closed"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to change status"); } finally { setBusy(false); } }
  async function updateSignup(id: string, status: VolunteerStatus) { setBusy(true); try { await setVolunteerSignupStatus(id, status); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update signup"); } finally { setBusy(false); } }
  return <div className="mx-auto w-full max-w-[1500px] pb-10"><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-2 text-sm font-bold text-raz-teal">{kind === "ngo" ? "ניהול ההזדמנויות של העמותה" : "ניהול הזדמנויות לקהילה"}</p><h1 className="text-4xl font-bold text-raz-dark md:text-6xl">ניהול מתנדבים</h1></div><button onClick={() => { setEditing(null); setOpen(true); }} className="flex min-h-11 items-center gap-2 rounded-xl bg-raz-teal px-6 py-3 font-bold text-white"><Plus size={18} />יצירת הזדמנות</button></div>{error && <p role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<section className="rounded-2xl bg-white p-5 shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b text-start text-raz-teal"><th className="p-3">הזדמנות</th><th className="p-3">קמפיין</th><th className="p-3">תאריך ומקום</th><th className="p-3">קיבולת</th><th className="p-3">נרשמים</th><th className="p-3">סטטוס</th><th className="p-3">פעולות</th></tr></thead><tbody>{opportunities.map((row) => <tr key={row.id} className="border-b"><td className="p-3 font-bold">{row.title}<p className="max-w-xs truncate font-normal text-slate-500">{row.description}</p></td><td className="p-3">{row.campaign_title ?? "—"}</td><td className="p-3">{row.starts_at ? new Date(row.starts_at).toLocaleString("he-IL") : "טרם נקבע"}<p className="text-slate-500">{row.location ?? ""}</p></td><td className="p-3">{row.capacity ?? "ללא הגבלה"}</td><td className="p-3"><button onClick={() => setSelected(row.id)} className="font-bold text-raz-teal">{row.signup_count}</button></td><td className="p-3">{row.status === "active" ? "פעילה" : row.status === "full" ? "מלאה" : "סגורה"}</td><td className="p-3 whitespace-nowrap"><button onClick={() => { setEditing(row); setOpen(true); }} className="me-2 rounded-lg bg-slate-100 p-2"><Pencil size={16} /></button><button disabled={busy} onClick={() => void close(row)} className="rounded-lg bg-slate-100 px-3 py-2">{row.status === "closed" ? "פתיחה" : "סגירה"}</button></td></tr>)}</tbody></table></div>{!opportunities.length && <div className="py-12 text-center text-slate-500">עדיין אין הזדמנויות התנדבות.</div>}</section>{selected && <section className="mt-6 rounded-2xl bg-white p-5 shadow-sm"><h2 className="mb-4 flex items-center gap-2 text-xl font-bold"><Users size={20} />נרשמים</h2><SignupTable rows={selectedSignups} busy={busy} onChange={updateSignup} /></section>}{open && <VolunteerOpportunityForm initial={draftFor(editing)} campaigns={campaigns} busy={busy} onClose={() => { setOpen(false); setEditing(null); }} onSave={(draft) => void save(draft)} />}</div>;
}
function SignupTable({ rows, busy, onChange }: { rows: VolunteerSignup[]; busy: boolean; onChange: (id: string, status: VolunteerStatus) => void }) { return <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b text-start text-raz-teal"><th className="p-3">שם</th><th className="p-3">אימייל</th><th className="p-3">טלפון</th><th className="p-3">קהילה מפנה</th><th className="p-3">סטטוס</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b"><td className="p-3 font-bold">{row.volunteer_name ?? "—"}</td><td className="p-3">{row.volunteer_email ?? "—"}</td><td className="p-3">{row.volunteer_phone ?? "—"}</td><td className="p-3">{row.community_name ?? "ישיר"}</td><td className="p-3"><select disabled={busy} value={row.status} onChange={(e) => onChange(row.id, e.target.value as VolunteerStatus)} className="rounded-lg border border-slate-200 p-2"><option value="registered">נרשם</option><option value="scheduled">נקבע מועד</option><option value="attended">הגיע</option><option value="cancelled">בוטל</option></select></td></tr>)}</tbody></table>{!rows.length && <p className="p-5 text-slate-500">אין נרשמים להזדמנות זו.</p>}</div>; }
