"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, Heart, Users } from "lucide-react";
import { formatNIS } from "@/lib/mock-data";
import type { Campaign, Community } from "@/lib/supabase/types";

type Tab = "updates" | "about";
type Props = { community: Community; campaigns: Campaign[]; lang: "he" | "en" };

export default function PublicCommunityProfileTabs({ community, campaigns, lang }: Props) {
  const [tab, setTab] = useState<Tab>("updates");
  const isEnglish = lang === "en";
  const labels: Record<Tab, string> = isEnglish ? { updates: "Latest updates", about: "About the community" } : { updates: "עדכונים אחרונים", about: "על הקהילה" };
  const name = isEnglish ? (community.name_en ?? community.name) : community.name;
  const date = new Intl.DateTimeFormat(isEnglish ? "en" : "he", { month: "long", year: "numeric" }).format(new Date(community.created_at));

  return <section className="mt-8 rounded-[2rem] border border-slate-100 bg-white p-5 shadow-[0_12px_30px_rgba(15,23,42,.06)] sm:p-8" dir={isEnglish ? "ltr" : "rtl"}>
    <div className="overflow-x-auto border-b border-slate-200"><div className="flex min-w-max gap-1">{(Object.keys(labels) as Tab[]).map((item) => <button key={item} type="button" onClick={() => setTab(item)} className={`px-4 py-3 text-sm font-bold transition-colors ${tab === item ? "border-b-2" : "text-slate-400 hover:text-slate-700"}`} style={tab === item ? { borderColor: community.color, color: community.color } : undefined}>{labels[item]}</button>)}</div></div>
    {tab === "updates" && <div className="pt-7"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-bold" style={{ color: community.color }}>{isEnglish ? "What is happening now" : "מה קורה עכשיו"}</p><h2 className="mt-1 text-2xl font-extrabold text-raz-dark">{isEnglish ? "Latest community updates" : "עדכונים אחרונים מהקהילה"}</h2></div><span className="rounded-full px-3 py-1 text-xs font-bold" style={{ backgroundColor: `${community.color}18`, color: community.color }}>{campaigns.length} {isEnglish ? "active campaigns" : "קמפיינים פעילים"}</span></div>{campaigns.length ? <div className="mt-6 grid gap-4 sm:grid-cols-2">{campaigns.map((campaign) => { const title = isEnglish ? (campaign.title_en ?? campaign.title) : campaign.title; const summary = isEnglish ? (campaign.short_desc_en ?? campaign.short_desc) : campaign.short_desc; return <Link key={campaign.id} href={`/campaign/${campaign.id}?community_id=${community.id}`} className="group rounded-2xl border border-slate-100 bg-slate-50 p-5 transition-all hover:-translate-y-0.5 hover:border-slate-200 hover:bg-white hover:shadow-md"><div className="flex items-start justify-between gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl text-2xl" style={{ backgroundColor: `${community.color}18` }}>{campaign.emoji}</span><span className="text-xs font-bold" style={{ color: community.color }}>{new Intl.DateTimeFormat(isEnglish ? "en" : "he", { month: "short", day: "numeric" }).format(new Date(campaign.updated_at))}</span></div><h3 className="mt-5 text-lg font-extrabold text-raz-dark">{title}</h3>{summary && <p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{summary}</p>}<span className="mt-5 inline-flex items-center gap-1 text-sm font-bold" style={{ color: community.color }}>{isEnglish ? "View campaign" : "לצפייה בקמפיין"}{isEnglish ? <ArrowRight size={16} className="transition-transform group-hover:translate-x-0.5" /> : <ArrowLeft size={16} className="transition-transform group-hover:-translate-x-0.5" />}</span></Link>; })}</div> : <Empty color={community.color} icon={<Heart size={24} />} text={isEnglish ? "Updates will appear here when the community launches activity." : "עדכונים יופיעו כאן כאשר הקהילה תצא לפעילות."} />}</div>}
    {tab === "about" && <div className="grid gap-7 pt-7 lg:grid-cols-[.78fr_1.22fr]"><aside className="rounded-2xl border p-5" style={{ borderColor: community.color }}><span className="flex h-20 w-20 items-center justify-center rounded-full text-3xl font-black text-white" style={{ backgroundColor: community.color }}>{name.slice(0, 1)}</span><h2 className="mt-4 text-xl font-extrabold text-raz-dark">{name}</h2><dl className="mt-5 space-y-3 text-sm"><Info icon={<Heart size={16} />} label={isEnglish ? "Raised together" : "גויסו יחד"} value={formatNIS(community.total_raised)} /><Info icon={<Users size={16} />} label={isEnglish ? "Community donors" : "תורמים בקהילה"} value={community.donors_count.toLocaleString()} /><Info icon={<CalendarDays size={16} />} label={isEnglish ? "Active since" : "פעילה מאז"} value={date} /></dl></aside><div><p className="text-sm font-bold" style={{ color: community.color }}>{isEnglish ? "Our community" : "הקהילה שלנו"}</p><h2 className="mt-2 text-2xl font-extrabold text-raz-dark">{isEnglish ? "A shared way to make an impact" : "דרך משותפת לעשות שינוי"}</h2><p className="mt-4 max-w-3xl whitespace-pre-line leading-8 text-slate-600">{community.description || (isEnglish ? "This community brings people together around meaningful giving and shared impact." : "הקהילה מחברת אנשים סביב נתינה משמעותית והשפעה משותפת.")}</p></div></div>}
  </section>;
}

function Info({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex items-center justify-between gap-4"><dt className="flex items-center gap-2 text-slate-400">{icon}{label}</dt><dd className="text-end font-bold text-slate-700">{value}</dd></div>; }
function Empty({ color, icon, text }: { color: string; icon: React.ReactNode; text: string }) { return <div className="mt-6 flex min-h-44 flex-col items-center justify-center gap-3 rounded-2xl bg-slate-50 px-5 text-center text-sm text-slate-500"><span style={{ color }}>{icon}</span>{text}</div>; }
