import LegalPage from "@/components/legal/LegalPage";

export default function PrivacyPage() {
  return <LegalPage
    he={{ title: "מדיניות פרטיות", updated: "30.08.2026", intro: "מדיניות זו מסבירה איזה מידע אישי Impactify אוספת, לשם מה היא משתמשת בו, ולמי הוא עשוי להימסר. מסירת מידע שאינו נדרש לפי דין היא מרצון; ללא פרטים מסוימים לא נוכל לספק חלק מהשירותים.", sections: [
      { title: "המידע שאנו אוספים", body: "פרטי חשבון וקשר כגון שם, דוא״ל וטלפון; פרטי תרומה וקמפיין; פעולות בשירות; ופניות שנשלחו בטופס קשר. בעת תשלום, ספק הסליקה עשוי לעבד פרטי תשלום. Impactify אינה שומרת את מספר כרטיס האשראי המלא או קוד האבטחה." },
      { title: "מטרות השימוש", body: "ניהול החשבון והתרומה, הפקת תיעוד וקבלות, מתן תמיכה, אבטחה ומניעת הונאה, שיפור השירות, עמידה בחובות משפטיות, ושליחת עדכונים רק בהתאם לבחירת המשתמש או לכל דין. לא נמכור מידע אישי." },
      { title: "שיתוף מידע", body: "מידע יימסר לעמותה הרלוונטית לצורך ניהול התרומה, לספקי סליקה ותשתית הפועלים עבורנו, ולרשויות מוסמכות כאשר הדין מחייב זאת. שיתוף נעשה רק במידה הנדרשת למטרה המתאימה ובכפוף לחובות סודיות ואבטחה." },
      { title: "דיווח תרומות", body: "כאשר תרומה מיועדת לעמותה בעלת אישור לפי סעיף 46, העמותה אחראית לדיווח כנדרש לרשות המסים, לרבות דיווח על תרומות וביטולים במערכת „תרומות ישראל” ככל שהדין מחייב. לשם כך ייתכן שיועברו לעמותה פרטי התרומה והזיהוי שנמסרו לה." },
      { title: "שמירה, אבטחה וזכויות", body: "אנו נוקטים אמצעי אבטחה סבירים ומחזיקים מידע רק כל עוד הוא נחוץ למטרות המדיניות, לחובות תיעוד או להגנה על זכויות. ניתן לבקש לעיין במידע אישי או לתקנו באמצעות טופס צור קשר, בכפוף לדין ולזיהוי הפונה." },
      { title: "עוגיות והעדפות", body: "אנו משתמשים בעוגיות ובאחסון מקומי חיוניים לצורך התחברות, אבטחה, בחירת שפה והפעלת השירות. עוגיות אנליטיקה או שיווק אינן מופעלות כברירת מחדל ומופעלות רק לאחר בחירה מפורשת. ניתן לאשר, לדחות או לשנות את הבחירה בכל עת באמצעות „הגדרות עוגיות” בתחתית דף הנחיתה." },
      { title: "קטגוריות עוגיות", body: "חיוניות: נדרשות לתפקוד, אבטחה והתחברות ואינן ניתנות לכיבוי דרך המערכת. אנליטיקה: נועדה למדידת שימוש ושיפור השירות. שיווק: נועדה למדידה ופרסום מותאם באמצעות צדדים שלישיים." },
      { title: "שינויים במדיניות", body: "מדיניות זו עשויה להתעדכן כדי לשקף שינוי בשירות, בספקים או בדין. במקרה של שינוי מהותי בבחירת העוגיות, נבקש בחירה מעודכנת לפני הפעלת קטגוריות לא־חיוניות." },
    ] }}
    en={{ title: "Privacy Policy", updated: "30 August 2026", intro: "This policy explains what personal information Impactify collects, why we use it, and with whom it may be shared. Providing information that is not required by law is voluntary; without certain details, we may be unable to provide parts of the service.", sections: [
      { title: "Information we collect", body: "Account and contact details such as name, email and phone number; donation and campaign details; activity in the service; and messages sent through the contact form. During payment, the payment provider may process payment details. Impactify does not store a full card number or security code." },
      { title: "How we use information", body: "To manage accounts and donations, create records and receipts, provide support, protect against fraud, improve the service, comply with legal obligations, and send updates only in line with the user's choice or applicable law. We do not sell personal information." },
      { title: "Sharing information", body: "Information is shared with the relevant nonprofit to manage a donation, with payment and infrastructure providers acting for us, and with authorized authorities where required by law. Sharing is limited to what is necessary for the relevant purpose and subject to confidentiality and security obligations." },
      { title: "Donation reporting", body: "Where a donation is made to a nonprofit approved under section 46, that nonprofit is responsible for any reporting required by the Israel Tax Authority, including reports of donations and cancellations in the Israel Donations system where required by law. Donation and identification details provided to the nonprofit may be shared for that purpose." },
      { title: "Retention, security and rights", body: "We use reasonable security measures and keep information only as long as it is needed for the purposes of this policy, recordkeeping duties, or protection of rights. You may request access to or correction of personal information through the contact form, subject to law and identity verification." },
      { title: "Cookies and preferences", body: "We use essential cookies and local storage for sign-in, security, language choice and operation of the service. Analytics and marketing cookies are off by default and are enabled only after an explicit choice. You can accept, reject or change your choice at any time through Cookie settings at the bottom of the landing page." },
      { title: "Cookie categories", body: "Essential cookies are required for operation, security and sign-in and cannot be disabled in the service. Analytics cookies measure usage and improve the service. Marketing cookies support third-party measurement and tailored advertising." },
      { title: "Changes to this policy", body: "This policy may be updated to reflect changes in the service, providers or law. If a material change affects cookie choices, we will request an updated choice before enabling non-essential categories." },
    ] }}
  />;
}
